/**
 * 座標エクスポートユーティリティ
 * ポリゴンとウェイポイントをGeoJSON、KML、DMS、CSV形式にエクスポート
 */

import type { CoordinateData } from '@/types/utmTypes'

// 座標点の型定義
export interface Coordinate {
  lat: number
  lng: number
  name?: string
  altitude?: number
  order?: number
}

// ポリゴンの型定義
export interface PolygonData {
  id: string
  name?: string
  coordinates: Array<[number, number]> // [lng, lat]
  properties?: Record<string, unknown>
}

// ウェイポイントの型定義
export interface WaypointData {
  id: string
  name?: string
  lat: number
  lng: number
  altitude?: number
  order?: number
  properties?: Record<string, unknown>
}

// エクスポート結果
export interface ExportResult {
  success: boolean
  content: string
  filename: string
  mimeType: string
  error?: string
}

/**
 * 10進度から度分秒（DMS）に変換
 */
function decimalToDMS(decimal: number, isLatitude: boolean): string {
  const absolute = Math.abs(decimal)
  const degrees = Math.floor(absolute)
  const minutesNotTruncated = (absolute - degrees) * 60
  const minutes = Math.floor(minutesNotTruncated)
  const seconds = ((minutesNotTruncated - minutes) * 60).toFixed(2)

  const direction = isLatitude
    ? decimal >= 0
      ? 'N'
      : 'S'
    : decimal >= 0
      ? 'E'
      : 'W'

  return `${degrees}°${minutes}'${seconds}"${direction}`
}

/**
 * 座標をDMS形式の文字列に変換
 */
export function formatCoordinateAsDMS(lat: number, lng: number): string {
  return `${decimalToDMS(lat, true)}, ${decimalToDMS(lng, false)}`
}

/**
 * GeoJSON形式でエクスポート
 */
export function exportToGeoJSON(
  polygons: PolygonData[],
  waypoints: WaypointData[],
  options: { pretty?: boolean; includeProperties?: boolean } = {}
): ExportResult {
  const { pretty = true, includeProperties = true } = options

  try {
    const features: GeoJSON.Feature[] = []

    // ポリゴンをFeatureとして追加
    polygons.forEach((polygon) => {
      // 座標をリング形式に変換（最初と最後を同じにする）
      const ring = [...polygon.coordinates]
      if (
        ring.length > 0 &&
        (ring[0][0] !== ring[ring.length - 1][0] ||
          ring[0][1] !== ring[ring.length - 1][1])
      ) {
        ring.push(ring[0])
      }

      const feature: GeoJSON.Feature = {
        type: 'Feature',
        geometry: {
          type: 'Polygon',
          coordinates: [ring],
        },
        properties: {
          id: polygon.id,
          name: polygon.name || `Polygon ${polygon.id}`,
          ...(includeProperties ? polygon.properties : {}),
        },
      }
      features.push(feature)
    })

    // ウェイポイントをPointとして追加
    waypoints.forEach((wp) => {
      const feature: GeoJSON.Feature = {
        type: 'Feature',
        geometry: {
          type: 'Point',
          coordinates:
            wp.altitude !== undefined
              ? [wp.lng, wp.lat, wp.altitude]
              : [wp.lng, wp.lat],
        },
        properties: {
          id: wp.id,
          name: wp.name || `WP${wp.order ?? ''}`,
          order: wp.order,
          altitude: wp.altitude,
          ...(includeProperties ? wp.properties : {}),
        },
      }
      features.push(feature)
    })

    // ウェイポイントをLineStringとしても追加（ルート表示用）
    if (waypoints.length >= 2) {
      const sortedWaypoints = [...waypoints].sort(
        (a, b) => (a.order ?? 0) - (b.order ?? 0)
      )
      const lineFeature: GeoJSON.Feature = {
        type: 'Feature',
        geometry: {
          type: 'LineString',
          coordinates: sortedWaypoints.map((wp) =>
            wp.altitude !== undefined
              ? [wp.lng, wp.lat, wp.altitude]
              : [wp.lng, wp.lat]
          ),
        },
        properties: {
          type: 'route',
          waypointCount: waypoints.length,
        },
      }
      features.push(lineFeature)
    }

    const geojson: GeoJSON.FeatureCollection = {
      type: 'FeatureCollection',
      features,
    }

    const content = pretty
      ? JSON.stringify(geojson, null, 2)
      : JSON.stringify(geojson)

    const timestamp = new Date().toISOString().slice(0, 10)
    return {
      success: true,
      content,
      filename: `flight-area-${timestamp}.geojson`,
      mimeType: 'application/geo+json',
    }
  } catch (error) {
    return {
      success: false,
      content: '',
      filename: '',
      mimeType: '',
      error: `GeoJSONエクスポートエラー: ${error}`,
    }
  }
}

/**
 * KML形式でエクスポート
 */
export function exportToKML(
  polygons: PolygonData[],
  waypoints: WaypointData[],
  options: { documentName?: string; includeAltitude?: boolean } = {}
): ExportResult {
  const { documentName = 'Flight Area', includeAltitude = true } = options

  try {
    let kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>${escapeXml(documentName)}</name>
    <description>Generated by KDDI Smart Drone Platform</description>

    <!-- スタイル定義 -->
    <Style id="polygonStyle">
      <LineStyle>
        <color>ff0000ff</color>
        <width>2</width>
      </LineStyle>
      <PolyStyle>
        <color>4d0000ff</color>
      </PolyStyle>
    </Style>
    <Style id="waypointStyle">
      <IconStyle>
        <Icon>
          <href>http://maps.google.com/mapfiles/kml/paddle/red-circle.png</href>
        </Icon>
      </IconStyle>
    </Style>
    <Style id="routeStyle">
      <LineStyle>
        <color>ff00ff00</color>
        <width>3</width>
      </LineStyle>
    </Style>
`

    // ポリゴン
    polygons.forEach((polygon, index) => {
      const coords = polygon.coordinates
        .map((c) => {
          return includeAltitude ? `${c[0]},${c[1]},0` : `${c[0]},${c[1]}`
        })
        .join('\n            ')

      // 閉じる座標を追加
      const firstCoord = polygon.coordinates[0]
      const closingCoord = includeAltitude
        ? `${firstCoord[0]},${firstCoord[1]},0`
        : `${firstCoord[0]},${firstCoord[1]}`

      kml += `
    <Placemark>
      <name>${escapeXml(polygon.name || `Polygon ${index + 1}`)}</name>
      <styleUrl>#polygonStyle</styleUrl>
      <Polygon>
        <outerBoundaryIs>
          <LinearRing>
            <coordinates>
            ${coords}
            ${closingCoord}
            </coordinates>
          </LinearRing>
        </outerBoundaryIs>
      </Polygon>
    </Placemark>
`
    })

    // ウェイポイント
    const sortedWaypoints = [...waypoints].sort(
      (a, b) => (a.order ?? 0) - (b.order ?? 0)
    )

    sortedWaypoints.forEach((wp) => {
      const alt = wp.altitude ?? 0
      kml += `
    <Placemark>
      <name>${escapeXml(wp.name || `WP${wp.order ?? ''}`)}</name>
      <styleUrl>#waypointStyle</styleUrl>
      <Point>
        <coordinates>${wp.lng},${wp.lat}${includeAltitude ? `,${alt}` : ''}</coordinates>
      </Point>
    </Placemark>
`
    })

    // ルートライン
    if (sortedWaypoints.length >= 2) {
      const routeCoords = sortedWaypoints
        .map((wp) => {
          const alt = wp.altitude ?? 0
          return includeAltitude
            ? `${wp.lng},${wp.lat},${alt}`
            : `${wp.lng},${wp.lat}`
        })
        .join('\n            ')

      kml += `
    <Placemark>
      <name>Flight Route</name>
      <styleUrl>#routeStyle</styleUrl>
      <LineString>
        <coordinates>
            ${routeCoords}
        </coordinates>
      </LineString>
    </Placemark>
`
    }

    kml += `
  </Document>
</kml>`

    const timestamp = new Date().toISOString().slice(0, 10)
    return {
      success: true,
      content: kml,
      filename: `flight-area-${timestamp}.kml`,
      mimeType: 'application/vnd.google-earth.kml+xml',
    }
  } catch (error) {
    return {
      success: false,
      content: '',
      filename: '',
      mimeType: '',
      error: `KMLエクスポートエラー: ${error}`,
    }
  }
}

/**
 * DMS形式でエクスポート（テキスト）
 */
export function exportToDMS(
  polygons: PolygonData[],
  waypoints: WaypointData[],
  options: { separator?: string; includeHeaders?: boolean } = {}
): ExportResult {
  const { separator = '\n', includeHeaders = true } = options

  try {
    const lines: string[] = []

    if (includeHeaders && polygons.length > 0) {
      lines.push('=== Polygons (DMS) ===')
      lines.push('')
    }

    // ポリゴン
    polygons.forEach((polygon, polygonIndex) => {
      lines.push(`--- ${polygon.name || `Polygon ${polygonIndex + 1}`} ---`)
      polygon.coordinates.forEach((coord, vertexIndex) => {
        const lat = coord[1]
        const lng = coord[0]
        const dms = formatCoordinateAsDMS(lat, lng)
        lines.push(`  V${vertexIndex + 1}: ${dms}`)
      })
      lines.push('')
    })

    if (includeHeaders && waypoints.length > 0) {
      lines.push('=== Waypoints (DMS) ===')
      lines.push('')
    }

    // ウェイポイント
    const sortedWaypoints = [...waypoints].sort(
      (a, b) => (a.order ?? 0) - (b.order ?? 0)
    )

    sortedWaypoints.forEach((wp) => {
      const dms = formatCoordinateAsDMS(wp.lat, wp.lng)
      const altStr = wp.altitude !== undefined ? ` (ALT: ${wp.altitude}m)` : ''
      lines.push(`${wp.name || `WP${wp.order ?? ''}`}: ${dms}${altStr}`)
    })

    const content = lines.join(separator)

    const timestamp = new Date().toISOString().slice(0, 10)
    return {
      success: true,
      content,
      filename: `flight-area-${timestamp}-dms.txt`,
      mimeType: 'text/plain',
    }
  } catch (error) {
    return {
      success: false,
      content: '',
      filename: '',
      mimeType: '',
      error: `DMSエクスポートエラー: ${error}`,
    }
  }
}

/**
 * CSV形式でエクスポート
 */
export function exportToCSV(
  polygons: PolygonData[],
  waypoints: WaypointData[],
  options: {
    includeHeader?: boolean
    coordinateFormat?: 'decimal' | 'dms'
    delimiter?: string
  } = {}
): ExportResult {
  const {
    includeHeader = true,
    coordinateFormat = 'decimal',
    delimiter = ',',
  } = options

  try {
    const lines: string[] = []

    // ウェイポイントCSV
    if (includeHeader) {
      if (coordinateFormat === 'dms') {
        lines.push(
          [
            'Name',
            'Order',
            'Latitude (DMS)',
            'Longitude (DMS)',
            'Altitude',
          ].join(delimiter)
        )
      } else {
        lines.push(
          ['Name', 'Order', 'Latitude', 'Longitude', 'Altitude'].join(delimiter)
        )
      }
    }

    const sortedWaypoints = [...waypoints].sort(
      (a, b) => (a.order ?? 0) - (b.order ?? 0)
    )

    sortedWaypoints.forEach((wp) => {
      const name = wp.name || `WP${wp.order ?? ''}`
      const order = wp.order ?? ''
      const lat =
        coordinateFormat === 'dms'
          ? decimalToDMS(wp.lat, true)
          : wp.lat.toFixed(8)
      const lng =
        coordinateFormat === 'dms'
          ? decimalToDMS(wp.lng, false)
          : wp.lng.toFixed(8)
      const alt = wp.altitude ?? ''

      lines.push([name, order, lat, lng, alt].join(delimiter))
    })

    // ポリゴン頂点CSV（別セクション）
    if (polygons.length > 0) {
      lines.push('') // 空行
      if (includeHeader) {
        if (coordinateFormat === 'dms') {
          lines.push(
            ['Polygon', 'Vertex', 'Latitude (DMS)', 'Longitude (DMS)'].join(
              delimiter
            )
          )
        } else {
          lines.push(
            ['Polygon', 'Vertex', 'Latitude', 'Longitude'].join(delimiter)
          )
        }
      }

      polygons.forEach((polygon, polygonIndex) => {
        const polygonName = polygon.name || `Polygon ${polygonIndex + 1}`
        polygon.coordinates.forEach((coord, vertexIndex) => {
          const lat =
            coordinateFormat === 'dms'
              ? decimalToDMS(coord[1], true)
              : coord[1].toFixed(8)
          const lng =
            coordinateFormat === 'dms'
              ? decimalToDMS(coord[0], false)
              : coord[0].toFixed(8)

          lines.push([polygonName, vertexIndex + 1, lat, lng].join(delimiter))
        })
      })
    }

    const content = lines.join('\n')

    const timestamp = new Date().toISOString().slice(0, 10)
    return {
      success: true,
      content,
      filename: `flight-area-${timestamp}.csv`,
      mimeType: 'text/csv',
    }
  } catch (error) {
    return {
      success: false,
      content: '',
      filename: '',
      mimeType: '',
      error: `CSVエクスポートエラー: ${error}`,
    }
  }
}

/**
 * ファイルダウンロードを実行
 */
export function downloadExportFile(result: ExportResult): boolean {
  if (!result.success) {
    console.error(result.error)
    return false
  }

  try {
    const blob = new Blob([result.content], { type: result.mimeType })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = result.filename
    document.body.appendChild(a)
    a.click()
    document.body.removeChild(a)
    URL.revokeObjectURL(url)
    return true
  } catch (error) {
    console.error('ファイルダウンロードエラー:', error)
    return false
  }
}

/**
 * クリップボードにコピー
 */
export async function copyToClipboard(result: ExportResult): Promise<boolean> {
  if (!result.success) {
    console.error(result.error)
    return false
  }

  try {
    await navigator.clipboard.writeText(result.content)
    return true
  } catch (error) {
    console.error('クリップボードコピーエラー:', error)
    return false
  }
}

/**
 * CoordinateData配列からWaypointData配列に変換
 */
export function coordinateDataToWaypoints(
  coordinates: CoordinateData[]
): WaypointData[] {
  return coordinates.map((coord, index) => ({
    id: `wp-${index}`,
    name: coord.name,
    lat: coord.latitude,
    lng: coord.longitude,
    altitude: coord.altitude,
    order: coord.order ?? index,
  }))
}

/**
 * XMLエスケープ
 */
function escapeXml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/**
 * 一括エクスポート（全形式）
 */
export function exportAll(
  polygons: PolygonData[],
  waypoints: WaypointData[]
): {
  geojson: ExportResult
  kml: ExportResult
  dms: ExportResult
  csv: ExportResult
} {
  return {
    geojson: exportToGeoJSON(polygons, waypoints),
    kml: exportToKML(polygons, waypoints),
    dms: exportToDMS(polygons, waypoints),
    csv: exportToCSV(polygons, waypoints),
  }
}
